name: Update Coinbase Sheet

on:
  workflow_dispatch:   # allows you to trigger manually
  schedule:
    - cron: "0 * * * *"   # runs every hour (adjust as needed)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          COINBASE_ORG_ID: ${{ secrets.COINBASE_ORG_ID }}
          COINBASE_KEY_ID: ${{ secrets.COINBASE_KEY_ID }}
          COINBASE_PRIVATE_KEY: ${{ secrets.COINBASE_PRIVATE_KEY }}
          SHEET_WEBHOOK_URL: ${{ secrets.SHEET_WEBHOOK_URL }}
          SHEET_SHARED_SECRET: ${{ secrets.SHEET_SHARED_SECRET }}
